
language: cpp
sudo: false

compiler:
  - gcc

install:
  - env
  # install CMake 3.3
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - echo "f3546812c11ce7f5d64dc132a566b749 *cmake-3.3.2-Linux-x86_64.tar.gz" > cmake_md5.txt
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.3.2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.3.2-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir libstratcom
  - git clone https://github.com/ComicSansMS/libstratcom.git libstratcom
  - cd libstratcom/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..
  - make

script:
  - cd ${TRAVIS_BUILD_DIR}/libstratcom/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..
  - make

after_script:
  - cd ${TRAVIS_BUILD_DIR}/libstratcom/build
  - make doxygen-doc
