
language: cpp
sudo: false

compiler:
  - gcc

install:
  - env

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir libstratcom
  - git clone https://github.com/ComicSansMS/libstratcom.git libstratcom
  - cd libstratcom/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..
  - make

script:
  - cd ${TRAVIS_BUILD_DIR}/libstratcom/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..
  - make

after_script:
  - cd ${TRAVIS_BUILD_DIR}/libstratcom/build
  - make doxygen-doc
