
language: cpp
sudo: false

compiler:
  - gcc
addons: &clang34
  apt:
    packages: clang-3.4
    sources: *sources

install:
  - gcc --version
  - clang --version
  - clang++ --version
  - which clang
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - wget http://cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar -xvf cmake-3.3.2.tar.gz > /dev/null
  - mkdir cmake-build && mkdir cmake-install
  - cd cmake-build
  - cmake -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/cmake-install -DCMAKE_CXX_COMPILE=clang++ -DCMAKE_C_COMPILER=clang ../cmake-3.3.2
  - ls -lha ${DEPS_DIR}/cmake-install
  
  - which cmake

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/ComicSansMS/GhulbusBase.git gbBase
  - cd gbBase
  - cd build
  - cmake ..

script:
  - make
  - make test
