
language: cpp
sudo: false

compiler:
  - gcc
addons: &clang34
  apt:
    packages:
        # compiler
      #- clang-3.6
      - g++-5
      - gcc-5
      - ninja-build
      # doxygen
      - doxygen
      - graphviz
      # mscgen is currently not whitelisted :(
      #- mscgen
      # third-party dependencies
      - libboost1.55-dev
      - libboost-date-time1.55-dev
      - libboost-log1.55-dev
      - libboost-thread1.55-dev
      - libboost-wave1.55-dev
      - libboost1.55-all-dev
    sources:
      - ubuntu-toolchain-r-test
      #- llvm-toolchain-precise-3.6
      - boost-latest

install:
  - gcc-5 --version
  #- clang-3.6 --version
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - wget http://cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar -xvf cmake-3.3.2.tar.gz > /dev/null
  - mkdir cmake-build && mkdir cmake-install
  - cd cmake-build
  - cmake
  - cmake -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/cmake-install -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 ../cmake-3.3.2 > cmake_configure.log
  - make -j 2 > cmake_compile.log
  - make install > cmake_install.log
  - ls -lha ${DEPS_DIR}/cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake
  - ${DEPS_DIR}/cmake-install/bin/cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -lha
  - git clone https://github.com/ComicSansMS/GhulbusBase.git gbBase
  - cd gbBase
  - cp ../CMakeLists.txt .
  - mkdir build-static-gcc5 && mkdir build-shared-gcc5 && mkdir build-static-clang36 && mkdir build-shared-clang36
  - cd build-static-gcc5
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
  - make
  - cd ../build-shared-gcc5
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
  - make
  #- cd ../build-static-clang36
  #- cmake -DCMAKE_CXX_COMPILER=clang++-3.6 -DCMAKE_C_COMPILER=clang-3.6 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
  #- make
  #- cd ../build-shared-clang36
  #- cmake -DCMAKE_CXX_COMPILER=clang++-3.6 -DCMAKE_C_COMPILER=clang-3.6 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
  #- make
  - cd ${TRAVIS_BUILD_DIR}/gbBase

script:
  - cd build-static-gcc5
  - make test
  - cd ../build-shared-gcc5
  - make test
  #- cd ../build-static-clang36
  #- make test
  #- cd ../build-shared-clang36
  #- make test

after_script:
  - cd ${TRAVIS_BUILD_DIR}/gbBase
  - cd build-static-gcc5
  - make doxygen-doc
