
language: cpp
sudo: false

compiler:
  - gcc
addons: &clang34
  apt:
    packages:
        # compiler
      - clang-3.4
      - g++-5
      - gcc-5
      - ninja-build
      # doxygen
      - doxygen
      - graphviz
      # mscgen is currently not whitelisted :(
      #- mscgen
      # third-party dependencies
      - libboost1.55-dev
      - libboost-date-time1.55-dev
      - libboost-log1.55-dev
      - libboost-thread1.55-dev
      - libboost-wave1.55-dev
      - libboost1.55-all-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - boost-latest

install:
  - gcc --version
  - clang --version
  - clang++ --version
  - which clang
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - wget http://cmake.org/files/v3.3/cmake-3.3.2.tar.gz
  - tar -xvf cmake-3.3.2.tar.gz > /dev/null
  - mkdir cmake-build && mkdir cmake-install
  - cd cmake-build
  - cmake
  - cmake -GNinja -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/cmake-install -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 ../cmake-3.3.2
  - ninja
  - ninja install
  - ls -lha ${DEPS_DIR}/cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake
  - ${DEPS_DIR}/cmake-install/bin/cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -lha
  - git clone https://github.com/ComicSansMS/GhulbusBase.git gbBase
  - cd gbBase
  - cp ../CMakeLists.txt .
  - mkdir build-static && mkdir build-shared
  - cd build-static
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DBUILD_SHARED_LIBS=OFF ..
  - make
  - cd ../build-shared
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DBUILD_SHARED_LIBS=ON ..
  - make
  - cd ..

script:
  - cd build-static
  - make test
  - cd ../build-shared
  - make test
  - cd ..

after_script:
  - cd build-static
  - make doxygen-doc
