
language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - cmake
      - cmake-data
      - doxygen
      - libudev-dev

install:
  - env
  - gcc --version
  - gcc-4.8 --version
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir libstratcom
  - git clone https://github.com/ComicSansMS/libstratcom.git libstratcom
  - cd libstratcom/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..
  - make

script:
  - cd ${TRAVIS_BUILD_DIR}/libstratcom/build
  - cmake -DBUILD_EXAMPLE_APPLICATIONS=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/INSTALL ..
  - make

after_script:
  - cd ${TRAVIS_BUILD_DIR}/libstratcom/build
  - make doxygen-doc
