
language: cpp
sudo: false


matrix:
  include:
    - env: COMPILER=g++-5 BUILD_TYPE=Debug BUILD_SHARED_LIBS=ON
    - compiler: gcc
    - addons: &gcc5
      apt:
        packages:
          - g++-5
          - gcc-5
          - doxygen
          - graphviz
          - libboost1.55-dev
          - libboost-date-time1.55-dev
          - libboost-log1.55-dev
          - libboost-thread1.55-dev
          - libboost-wave1.55-dev
          - libboost1.55-all-dev
        sources: &sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
          - boost-latest
    - env: COMPILER=clang++-3.6 BUILD_TYPE=Debug BUILD_SHARED_LIBS=ON
    - compiler: clang
    - addons: &clang36
      apt:
        packages:
          - clang-3.6
          - doxygen
          - graphviz
          - libboost1.55-dev
          - libboost-date-time1.55-dev
          - libboost-log1.55-dev
          - libboost-thread1.55-dev
          - libboost-wave1.55-dev
          - libboost1.55-all-dev
        sources: *sources

install:
  - which ${COMPILER}
  - ${COMPILER} --version
  - env
  # install CMake 3.3
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - echo "f3546812c11ce7f5d64dc132a566b749 *cmake-3.3.2-Linux-x86_64.tar.gz" > cmake_md5.txt
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.3.2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.3.2-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/ComicSansMS/GhulbusBase.git gbBase
  - cd gbBase
  - cp ../CMakeLists.txt .
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} ..
  - make
#  - mkdir build-static-gcc5 && mkdir build-shared-gcc5 && mkdir build-static-clang36 && mkdir build-shared-clang36
#  - cd build-static-gcc5
#  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -DGB_GENERATE_COVERAGE_INFO=ON -DGCOV_COMMAND=gcov-5 ..
#  - make
#  - find .
#  - cd ../build-shared-gcc5
#  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
#  - make
#  - cd ../build-static-clang36
#  - cmake -DCMAKE_CXX_COMPILER=clang++-3.6 -DCMAKE_C_COMPILER=clang-3.6 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
#  - make
#  - cd ../build-shared-clang36
#  - cmake -DCMAKE_CXX_COMPILER=clang++-3.6 -DCMAKE_C_COMPILER=clang-3.6 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
#  - make
  - cd ${TRAVIS_BUILD_DIR}/gbBase

script:
  - cd build
  - make test
#  - make gbBase_TestCoverage
#  - gcov-5 -o ./CMakeFiles/gbBase.dir/src/Assert.cpp.gcno Assert.cpp
#  - gcov-5 -o ./CMakeFiles/gbBase.dir/src/Log.cpp.gcno Log.cpp
#  - gcov-5 -o ./CMakeFiles/gbBase.dir/src/LogHandlers.cpp.gcno LogHandlers.cpp
#  - cd ../build-shared-gcc5
#  - make test
#  - cd ../build-static-clang36
#  - make test
#  - cd ../build-shared-clang36
#  - make test

after_script:
  - cd ${TRAVIS_BUILD_DIR}/gbBase
  - cd build
  - make doxygen-doc

after_success:
  - bash <(curl -s https://codecov.io/bash)
